source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'pg'
gem 'inherited_resources', '~> 1.4.1'
gem 'simple_form'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'haml'
gem 'shoulda', '~> 3.3.2'
gem 'rspec-rails', '~> 2.0'
gem 'sass-rails', '>= 3.2' # sass-rails needs to be higher than 3.2
gem 'bootstrap-sass', '~> 3.1.1'
gem 'rails_serve_static_assets'
gem 'devise'
gem 'acts-as-taggable-on'
gem 'factory_girl_rails'
